import { createContext, useContext, useEffect, useState, useCallback, useRef } from 'react'
import { registerAppMaker } from '../services/authService'

const AuthContext = createContext(null)
const STORAGE_KEY = 'banksampah_session'

// Session: { appKey, token, role: 'nasabah' | 'admin' | null, user }
export function AuthProvider({ children }) {
  const [session, setSession] = useState(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY)
      const parsed = raw ? JSON.parse(raw) : null
      console.log('[AuthContext] Inisialisasi session awal dari localStorage:', parsed)
      return (
        parsed || {
          appKey: import.meta.env.VITE_APP_KEY || null,
          token: null,
          role: null,
          user: null,
        }
      )
    } catch (e) {
      console.error('[AuthContext] Error parsing localStorage session saat init:', e)
      return { appKey: null, token: null, role: null, user: null }
    }
  })

  const [isInitializing, setIsInitializing] = useState(!session.appKey)
  const [initError, setInitError] = useState(null)
  const isFetchingRef = useRef(false)

  // Persist session to localStorage
  useEffect(() => {
    console.log('[AuthContext] Menyimpan session terbaru ke localStorage:', session)
    localStorage.setItem(STORAGE_KEY, JSON.stringify(session))
  }, [session])

  // Auto-register App Maker on initial load if appKey is empty
  const autoRegisterAppMaker = useCallback(async () => {
    if (session.appKey || isFetchingRef.current) {
      setIsInitializing(false)
      return
    }

    isFetchingRef.current = true
    setIsInitializing(true)
    setInitError(null)

    try {
      const timestamp = Date.now()
      const makerPayload = {
        email: `siswa-${timestamp}@dummy.local`,
        password: 'autogenerated123',
        namaSiswa: 'Siswa RPL',
        kelas: 'XII RPL',
        namaApp: 'Bank Sampah Digital',
      }
      console.log('[AuthContext] Mendaftarkan App Maker baru otomatis:', makerPayload)

      const res = await registerAppMaker(makerPayload)
      console.log('[AuthContext] Response registrasi App Maker:', res.data)

      const receivedKey =
        res.data?.data?.appKey ||
        res.data?.appKey ||
        res.data?.data?.key ||
        res.data?.key

      if (!receivedKey) {
        throw new Error('App Key tidak ditemukan di dalam respons server.')
      }

      console.log('[AuthContext] App Key baru didapatkan:', receivedKey)
      setSession((prev) => ({ ...prev, appKey: receivedKey }))
      setIsInitializing(false)
    } catch (err) {
      console.error('[AuthContext] Gagal inisialisasi App Maker:', err.response || err)
      const msg =
        err.response?.data?.message ||
        err.response?.data?.error ||
        err.message ||
        'Gagal menginisialisasi App Key. Periksa koneksi internet Anda.'
      setInitError(msg)
      setIsInitializing(false)
    } finally {
      isFetchingRef.current = false
    }
  }, [session.appKey])

  useEffect(() => {
    if (!session.appKey) {
      autoRegisterAppMaker()
    } else {
      setIsInitializing(false)
    }
  }, [session.appKey, autoRegisterAppMaker])

  const login = ({ token, role, user }) => {
    console.log('[AuthContext] Menjalankan login():', { token, role, user })
    setSession((prev) => {
      const nextSession = { ...prev, token, role, user }
      console.log('[AuthContext] State session setelah login():', nextSession)
      return nextSession
    })
  }

  const setAppKey = (appKey) => {
    console.log('[AuthContext] Menjalankan setAppKey():', appKey)
    setSession((prev) => ({ ...prev, appKey }))
  }

  const logout = () => {
    console.log('[AuthContext] Menjalankan logout()')
    setSession((prev) => ({ appKey: prev.appKey, token: null, role: null, user: null }))
  }

  const isGuest = !session.token

  return (
    <AuthContext.Provider
      value={{
        session,
        login,
        logout,
        setAppKey,
        isGuest,
        isInitializing,
        initError,
        retryInit: autoRegisterAppMaker,
      }}
    >
      {children}
    </AuthContext.Provider>
  )
}

export function useAuth() {
  const ctx = useContext(AuthContext)
  if (!ctx) throw new Error('useAuth must be used within AuthProvider')
  return ctx
}
